### ISSUE TITLE
error in building docker images.

### ISSUE THREAD

**Issue by prasenforu** [duyanghao/velero-volume-controller#4]
Getting error when building docker images.

```
Step 16/19 : WORKDIR /go/bin
 ---> bf533388eca8
Removing intermediate container ccd67254bac3
Step 17/19 : COPY --from=0 /go/bin /go/bin
Unknown flag: from
make: *** [dockerfiles.build] Error 1
```

Do you have any ready docker image ?

**Comment by duyanghao** [comment]
@prasenforu I guess you'd better upgrade your docker version since [Multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) are a new feature requiring Docker 17.05 or higher on the daemon and client. And you can get docker image [here](https://hub.docker.com/repository/docker/dyhfighter/velero-volume-controller).

**Comment by prasenforu** [comment]
thanks :)
