### ISSUE TITLE
restore pvs of cluster

### ISSUE THREAD

**Issue by LilyaBu** [duyanghao/velero-volume-controller#5]
Hello, @duyanghao!
I would like to backup whole cluster with velero and velero-volume-controller.
Since velero-volume-controller pod is running before 
`vlero backup create..`, 
all pvc binded to pods will be backed up by velero.
What do you think about backup of pvc, that are not binded to any pod at moment of backup creating?
What do you think about backup of pv without binding to any pvc at moment of backup creaing?
As for restoring of pvs, pvcs from backup - is it correct that before run
`velero restore create..` 
cluster admin must delete all resources of cluster since velero can not load existing resources?
Thank you.

**Comment by duyanghao** [comment]
> What do you think about backup of pvc, that are not binded to any pod at moment of backup creating?
> What do you think about backup of pv without binding to any pvc at moment of backup creaing?

@LilyaBu `velero backup` will backup all pods with volumes when it is created, and it will ignore all PVCs and PVs that are not yet bound to any pods.
To solve this problem, you'd better use regularly scheduled backups in a production environment since `velero's restic integration` pvc backup is incremental:
```
$ velero schedule create backup-tutorial --schedule="*/2 * * * *"
$ velero schedule get  
NAME              STATUS    CREATED                         SCHEDULE      BACKUP TTL   LAST BACKUP   SELECTOR
backup-tutorial   Enabled   2020-03-25 14:18:34 +0800 CST   */2 * * * *   720h0m0s     8s ago        <none>
$ velero backup get
NAME                             STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
backup-tutorial-20200325062029   Completed   2020-03-25 14:20:29 +0800 CST   29d       default            <none>
backup-tutorial-20200325061834   Completed   2020-03-25 14:18:34 +0800 CST   29d       default            <none>
```
> As for restoring of pvs, pvcs from backup - is it correct that before run
velero restore create..
cluster admin must delete all resources of cluster since velero can not load existing resources?

Yes, you have to delete all resources since `velero restore create --from-backup xxx --include-resources persistentvolumeclaims,persistentvolumes` will do nothing for the existing pvs that we want to restore.

**Comment by duyanghao** [comment]
@LilyaBu Close this Issue, and feel free to come back if you have any more questions.
